package com.engitano.dynamof.syntax


trait AllSyntax extends TableSyntax with ToScalarAttrInstances with FilterSyntax with ToPredicateInstances with IsPrimaryKeySyntax with FieldNamesSyntax with DynamoOpsSyntax with FreeApplicativeOpsSyntax